#!/bin/sh
#
# Rename files from scryfall to remove unicode filename

mv oe01-9★-make-yourself-useful.png oe01-9-make-yourself-useful.png
mv oe01-8★-know-evil.png oe01-8-know-evil.png
mv oe01-7★-for-each-of-you-a-gift.png oe01-7-for-each-of-you-a-gift.png
mv oe01-6★-every-dream-a-nightmare.png oe01-6-every-dream-a-nightmare.png
mv oe01-5★-delight-in-the-hunt.png oe01-5-delight-in-the-hunt.png
mv oe01-4★-choose-your-demise.png oe01-4-choose-your-demise.png
mv oe01-3★-bow-to-my-command.png oe01-3-bow-to-my-command.png
mv oe01-2★-behold-my-grandeur.png oe01-2-behold-my-grandeur.png
mv oe01-20★-when-will-you-learn.png oe01-20-when-will-you-learn.png
mv oe01-1★-because-i-have-willed-it.png oe01-1-because-i-have-willed-it.png
mv oe01-19★-what-s-yours-is-now-mine.png oe01-19-what-s-yours-is-now-mine.png
mv oe01-18★-this-world-belongs-to-me.png oe01-18-this-world-belongs-to-me.png
mv oe01-17★-there-is-no-refuge.png oe01-17-there-is-no-refuge.png
mv oe01-16★-a-reckoning-approaches.png oe01-16-a-reckoning-approaches.png
mv oe01-15★-power-without-equal.png oe01-15-power-without-equal.png
mv oe01-14★-pay-tribute-to-me.png oe01-14-pay-tribute-to-me.png
mv oe01-13★-no-one-will-hear-your-cries.png oe01-13-no-one-will-hear-your-cries.png
mv oe01-12★-my-laughter-echoes.png oe01-12-my-laughter-echoes.png
mv oe01-11★-my-forces-are-innumerable.png oe01-11-my-forces-are-innumerable.png
mv oe01-10★-the-mighty-will-fall.png oe01-10-the-mighty-will-fall.png
mv oarc-9★-embrace-my-diabolical-vision.png oarc-9-embrace-my-diabolical-vision.png
mv oarc-8★-a-display-of-my-dark-power.png oarc-8-a-display-of-my-dark-power.png
mv oarc-7★-the-dead-shall-serve.png oarc-7-the-dead-shall-serve.png
mv oarc-6★-dance-pathetic-marionette.png oarc-6-dance-pathetic-marionette.png
mv oarc-5★-choose-your-champion.png oarc-5-choose-your-champion.png
mv oarc-4★-behold-the-power-of-destruction.png oarc-4-behold-the-power-of-destruction.png
mv oarc-45★-your-will-is-not-your-own.png oarc-45-your-will-is-not-your-own.png
mv oarc-44★-your-puny-minds-cannot-fathom.png oarc-44-your-puny-minds-cannot-fathom.png
mv oarc-43★-your-fate-is-thrice-sealed.png oarc-43-your-fate-is-thrice-sealed.png
mv oarc-42★-which-of-you-burns-brightest.png oarc-42-which-of-you-burns-brightest.png
mv oarc-41★-the-very-soil-shall-shake.png oarc-41-the-very-soil-shall-shake.png
mv oarc-40★-tooth-claw-and-tail.png oarc-40-tooth-claw-and-tail.png
mv oarc-3★-approach-my-molten-realm.png oarc-3-approach-my-molten-realm.png
mv oarc-39★-surrender-your-thoughts.png oarc-39-surrender-your-thoughts.png
mv oarc-38★-rotted-ones-lay-siege.png oarc-38-rotted-ones-lay-siege.png
mv oarc-37★-roots-of-all-evil.png oarc-37-roots-of-all-evil.png
mv oarc-36★-realms-befitting-my-majesty.png oarc-36-realms-befitting-my-majesty.png
mv oarc-35★-the-pieces-are-coming-together.png oarc-35-the-pieces-are-coming-together.png
mv oarc-34★-only-blood-ends-your-nightmares.png oarc-34-only-blood-ends-your-nightmares.png
mv oarc-33★-nothing-can-stop-me-now.png oarc-33-nothing-can-stop-me-now.png
mv oarc-32★-nature-shields-its-own.png oarc-32-nature-shields-its-own.png
mv oarc-31★-nature-demands-an-offering.png oarc-31-nature-demands-an-offering.png
mv oarc-30★-my-wish-is-your-command.png oarc-30-my-wish-is-your-command.png
mv oarc-2★-all-shall-smolder-in-my-wake.png oarc-2-all-shall-smolder-in-my-wake.png
mv oarc-29★-my-undead-horde-awakens.png oarc-29-my-undead-horde-awakens.png
mv oarc-28★-my-genius-knows-no-bounds.png oarc-28-my-genius-knows-no-bounds.png
mv oarc-27★-my-crushing-masterstroke.png oarc-27-my-crushing-masterstroke.png
mv oarc-26★-mortal-flesh-is-weak.png oarc-26-mortal-flesh-is-weak.png
mv oarc-25★-may-civilization-collapse.png oarc-25-may-civilization-collapse.png
mv oarc-24★-look-skyward-and-despair.png oarc-24-look-skyward-and-despair.png
mv oarc-23★-know-naught-but-fire.png oarc-23-know-naught-but-fire.png
mv oarc-22★-the-iron-guardian-stirs.png oarc-22-the-iron-guardian-stirs.png
mv oarc-21★-introductions-are-in-order.png oarc-21-introductions-are-in-order.png
mv oarc-20★-into-the-earthen-maw.png oarc-20-into-the-earthen-maw.png
mv oarc-1★-all-in-good-time.png oarc-1-all-in-good-time.png
mv oarc-19★-ignite-the-cloneforge.png oarc-19-ignite-the-cloneforge.png
mv oarc-18★-i-know-all-i-see-all.png oarc-18-i-know-all-i-see-all.png
mv oarc-17★-i-delight-in-your-convulsions.png oarc-17-i-delight-in-your-convulsions.png
mv oarc-16★-i-call-on-the-ancient-magics.png oarc-16-i-call-on-the-ancient-magics.png
mv oarc-15★-i-bask-in-your-silent-awe.png oarc-15-i-bask-in-your-silent-awe.png
mv oarc-14★-feed-the-machine.png oarc-14-feed-the-machine.png
mv oarc-13★-the-fate-of-the-flammable.png oarc-13-the-fate-of-the-flammable.png
mv oarc-12★-evil-comes-to-fruition.png oarc-12-evil-comes-to-fruition.png
mv oarc-11★-every-last-vestige-shall-rot.png oarc-11-every-last-vestige-shall-rot.png
mv oarc-10★-every-hope-shall-vanish.png oarc-10-every-hope-shall-vanish.png
